# ===================================
#  Form Behavior Config
# ===================================

form: @/modules/backend/models/editorsettings/fields.yaml
modelClass: Backend\Models\EditorSettings
defaultRedirect: system/emailtemplates
