# ===================================
#  Form Behavior Config
# ===================================

name: backend::lang.user.group.name
form: @/modules/backend/models/group/fields.yaml
modelClass: Backend\Models\UserGroup
defaultRedirect: backend/groups

create:
    redirect: backend/groups/update/:id
    redirectClose: backend/groups

update:
    redirect: backend/groups
    redirectClose: backend/groups
